// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Instruction.proto

// Protobuf Java Version: 3.25.5
package com.szhuima.zim.api.proto.instruction;

public final class InstructionProto {
  private InstructionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code InstructionType}
   */
  public enum InstructionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ACK = 0;</code>
     */
    ACK(0),
    /**
     * <code>HEAR_BEAT = 1;</code>
     */
    HEAR_BEAT(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ACK = 0;</code>
     */
    public static final int ACK_VALUE = 0;
    /**
     * <code>HEAR_BEAT = 1;</code>
     */
    public static final int HEAR_BEAT_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static InstructionType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static InstructionType forNumber(int value) {
      switch (value) {
        case 0: return ACK;
        case 1: return HEAR_BEAT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<InstructionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        InstructionType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<InstructionType>() {
            public InstructionType findValueByNumber(int number) {
              return InstructionType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.szhuima.zim.api.proto.instruction.InstructionProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final InstructionType[] VALUES = values();

    public static InstructionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private InstructionType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:InstructionType)
  }

  public interface InstructionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Instruction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.InstructionType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.InstructionType type = 1;</code>
     * @return The type.
     */
    com.szhuima.zim.api.proto.instruction.InstructionProto.InstructionType getType();

    /**
     * <code>int64 msgId = 2;</code>
     * @return The msgId.
     */
    long getMsgId();
  }
  /**
   * Protobuf type {@code Instruction}
   */
  public static final class Instruction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Instruction)
      InstructionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Instruction.newBuilder() to construct.
    private Instruction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Instruction() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Instruction();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.szhuima.zim.api.proto.instruction.InstructionProto.internal_static_Instruction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.szhuima.zim.api.proto.instruction.InstructionProto.internal_static_Instruction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction.class, com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_ = 0;
    /**
     * <code>.InstructionType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.InstructionType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public com.szhuima.zim.api.proto.instruction.InstructionProto.InstructionType getType() {
      com.szhuima.zim.api.proto.instruction.InstructionProto.InstructionType result = com.szhuima.zim.api.proto.instruction.InstructionProto.InstructionType.forNumber(type_);
      return result == null ? com.szhuima.zim.api.proto.instruction.InstructionProto.InstructionType.UNRECOGNIZED : result;
    }

    public static final int MSGID_FIELD_NUMBER = 2;
    private long msgId_ = 0L;
    /**
     * <code>int64 msgId = 2;</code>
     * @return The msgId.
     */
    @java.lang.Override
    public long getMsgId() {
      return msgId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.szhuima.zim.api.proto.instruction.InstructionProto.InstructionType.ACK.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (msgId_ != 0L) {
        output.writeInt64(2, msgId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.szhuima.zim.api.proto.instruction.InstructionProto.InstructionType.ACK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (msgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, msgId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction)) {
        return super.equals(obj);
      }
      com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction other = (com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction) obj;

      if (type_ != other.type_) return false;
      if (getMsgId()
          != other.getMsgId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgId());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Instruction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Instruction)
        com.szhuima.zim.api.proto.instruction.InstructionProto.InstructionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.szhuima.zim.api.proto.instruction.InstructionProto.internal_static_Instruction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.szhuima.zim.api.proto.instruction.InstructionProto.internal_static_Instruction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction.class, com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction.Builder.class);
      }

      // Construct using com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        type_ = 0;
        msgId_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.szhuima.zim.api.proto.instruction.InstructionProto.internal_static_Instruction_descriptor;
      }

      @java.lang.Override
      public com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction getDefaultInstanceForType() {
        return com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction.getDefaultInstance();
      }

      @java.lang.Override
      public com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction build() {
        com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction buildPartial() {
        com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction result = new com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.msgId_ = msgId_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction) {
          return mergeFrom((com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction other) {
        if (other == com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getMsgId() != 0L) {
          setMsgId(other.getMsgId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                msgId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>.InstructionType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.InstructionType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.InstructionType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.szhuima.zim.api.proto.instruction.InstructionProto.InstructionType getType() {
        com.szhuima.zim.api.proto.instruction.InstructionProto.InstructionType result = com.szhuima.zim.api.proto.instruction.InstructionProto.InstructionType.forNumber(type_);
        return result == null ? com.szhuima.zim.api.proto.instruction.InstructionProto.InstructionType.UNRECOGNIZED : result;
      }
      /**
       * <code>.InstructionType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.szhuima.zim.api.proto.instruction.InstructionProto.InstructionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.InstructionType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private long msgId_ ;
      /**
       * <code>int64 msgId = 2;</code>
       * @return The msgId.
       */
      @java.lang.Override
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <code>int64 msgId = 2;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(long value) {

        msgId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 msgId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Instruction)
    }

    // @@protoc_insertion_point(class_scope:Instruction)
    private static final com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction();
    }

    public static com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Instruction>
        PARSER = new com.google.protobuf.AbstractParser<Instruction>() {
      @java.lang.Override
      public Instruction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Instruction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Instruction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.szhuima.zim.api.proto.instruction.InstructionProto.Instruction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Instruction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Instruction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Instruction.proto\"<\n\013Instruction\022\036\n\004ty" +
      "pe\030\001 \001(\0162\020.InstructionType\022\r\n\005msgId\030\002 \001(" +
      "\003*)\n\017InstructionType\022\007\n\003ACK\020\000\022\r\n\tHEAR_BE" +
      "AT\020\001B;\n%com.szhuima.zim.api.proto.instru" +
      "ctionB\020InstructionProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Instruction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Instruction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Instruction_descriptor,
        new java.lang.String[] { "Type", "MsgId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
