spring:
  application:
    name: websocket-server

  main:
    web-application-type: none

grpc:
  server:
    port: 7763

zim:
  server:
    websocket:
      port: 8899

logging:
  level:
    root: info
